name: 'AdvancedServerList-OG'
author: 'Andre_601'
version: '${version}'
description: '${description}'

main: 'ch.andre601.advancedserverlist.paper.PaperCore'

api-version: '1.19'

folia-supported: false

dependencies:
  server:
    ViaVersion:
      load: BEFORE
      required: true
      join-classpath: true
    Maintenance:
      load: BEFORE
      required: true
      join-classpath: true

# The below stuff is NOT used by Paper plugin.
commands:
  advancedserverlist:
    description: 'Main command of AdvancedServerList-OG'
    usage: '/<command> [help|reload]'
    aliases:
      - 'asl'
    permission: 'advancedserverlist.admin'

# This is actually supported(?)
permissions:
  advancedserverlist.*:
    description: 'Grants access to all permissions'
    default: op
    children:
      - 'advancedserverlist.admin'
  advancedserverlist.admin:
    description: 'Grants access to all permissions'
    default: op
    children:
      - 'advancedserverlist.command.*'
  advancedserverlist.command.*:
    description: 'Grants access to all commands'
    default: op
    children:
      - 'advancedserverlist.command.help'
      - 'advancedserverlist.command.reload'
  advancedserverlist.command.help:
    description: 'Grants access to /asl help'
    default: op
  advancedserverlist.command.reload:
    description: 'Grants access to /asl reload'
    default: op
